name: Build Projects

on:
  push:
    branches:
      - add-tizen-handler
  pull_request:
    branches:
      - add-tizen-handler

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: check-action after checkout
      run: |
      ls .github/workflows
      git branch -a
    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-rc.1.21463.6'
        include-prerelease: true
    - name: Install Tizen workload
      run: |
        dotnet nuget add source -n nuget https://api.nuget.org/v3/index.json
        curl -sSL https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.sh | bash /dev/stdin -v 6.5.100-rc.1.92
    - name: Build
      env:
        PULLREQUEST_ID: ${{ github.event.number }}
      run: |
        dotnet new sln -n Microsoft.Maui.Tizen-net6
        dotnet sln Microsoft.Maui.Tizen-net6.sln add src/Core/src/Core-net6.csproj src/Controls/src/Core/Controls.Core-net6.csproj src/Controls/src/Xaml/Controls.Xaml-net6.csproj  src/Compatibility/Core/src/Compatibility-net6.csproj src/Essentials/src/Essentials-net6.csproj src/BlazorWebView/src/Maui/Microsoft.AspNetCore.Components.WebView.Maui.csproj
        dotnet build Microsoft.Maui.Tizen-net6.sln -property:MauiPlatforms=net6.0-tizen
      working-directory: .
